version: '3'
services:
  web:
    build:
      context: .  # Path where is the project
      dockerfile: Dockerfile.dev #Path where is the Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .  # Path where is the project
      dockerfile: Dockerfile.dev #Path where is the Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    