sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_4491bbd041e7_key -iv $encrypted_4491bbd041e7_iv -in multi-k8s-348609-28ed82e4ae1c.json.enc -out multi-k8s-348609-28ed82e4ae1c.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-348609-28ed82e4ae1c.json
  - gcloud config set project multi-k8s-348609
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t marodrigues20/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true marodrigues20/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

  
